### ISSUE TITLE
Expand children of Show entity

### ISSUE THREAD

**Issue by puppetSpace** [frecar/epguides-api#70]
Are there any plans to implement an odata like way to expand the children of the Show entity?
I'm creating an application that displays the shows that are on this week, with the episode data.
I'm using the URI http://epguides.frecar.no/show/ to get all shows. In this data there is a reference to the next episode. So now I have to loop over every show and make a request for the next episode.
That takes a while.
Therefore it would be easier todo something like this: https://epguides.frecar.no/show/?$expand=next_episode. This way I only have to make 1 call to get the shows and the data for the next episode.

**Comment by frecar** [comment]
Hi @puppetSpace - this is a good idea, I can add this if this is still relevant for you.

**Comment by puppetSpace** [comment]
It's not relevant for me anymore. I kinda solved it by using an azure webjob to retrieve the data every night and cache it. This way my application can access the data quickly.
But thanks for the reply and the effort you were wiling to do.
This is a great API.
