### ISSUE TITLE
the public API is showing episode not found for many many TV shows

### ISSUE THREAD

**Issue by justbill2020** [frecar/epguides-api#93]
```{"error": "Episode not found"}``` error for the following shows

http://epguides.frecar.no/show/bigbangtheory/next/
http://epguides.frecar.no/show/gameofthrones/next/
http://epguides.frecar.no/show/thewalkingdead/next/
http://epguides.frecar.no/show/doctorwho/next/
http://epguides.frecar.no/show/conviction/next/
http://epguides.frecar.no/show/lethalweapon/next/
http://epguides.frecar.no/show/houseofcards/next/
http://epguides.frecar.no/show/rickandmorty/next/

however, "This is us" works
http://epguides.frecar.no/show/thisisus/next/

**Comment by curiousgabel** [comment]
Same when getting specific episode information (e.g. http://epguides.frecar.no/show/Futurama/06/15/).

However, the info seems to work: http://epguides.frecar.no/show/Futurama/info/
`{"title": "Futurama", "imdb_id": "tt0149460", "epguide_name": "futurama"}`

**Comment by curiousgabel** [comment]
Issue appears to be resolved at this time.

**Comment by justbill2020** [comment]
Not resolved for next commands listed above

**Comment by justbill2020** [comment]
Ok Rick and Marty not working others are... closing issue

**Comment by frecar** [comment]
@justbill2020 - the reason it shows "No episode found" is that the next episode isn't announced. Maybe we should have a more specific message in this case.

**Comment by justbill2020** [comment]
Perhaps TBD.... btw you did have an issue that is now resolved but a TBD would be nice... also some response if final episode aired like a cancelled show...

Sent from my iPhone

On Jan 15, 2017, at 8:39 AM, Fredrik Carlsen <notifications@github.com<mailto:notifications@github.com>> wrote:


@justbill2020<https://github.com/justbill2020> - the reason it shows "No episode found" is that the next episode isn't announced. Maybe we should have a more specific message in this case.

-
