### ISSUE TITLE
right now i'm getting bad gateway

### ISSUE THREAD

**Issue by justbill2020** [frecar/epguides-api#94]
http://epguides.frecar.no/show/ delivers `bad gateway 502`
![image](https://cloud.githubusercontent.com/assets/13437861/22185018/c80f8f46-e0a2-11e6-8c70-f3f6598dddc5.png)
using https returns` ssl error`
![image](https://cloud.githubusercontent.com/assets/13437861/22185023/ea056184-e0a2-11e6-8b44-30445a188e41.png)
in addition, every show's next which yesterday delivered results is now returning `{"error": "Episode not found"}`
![image](https://cloud.githubusercontent.com/assets/13437861/22185034/2f630830-e0a3-11e6-9569-b5fd8ca25865.png)

i would love to contribute to this project...

**Comment by frecar** [comment]
Is this resolved @justbill2020 ?

**Comment by justbill2020** [comment]
this comes and goes... it works and then it doesn't i don't know why...
