### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by fabbrus97** [frecar/epguides-api#98]
Good evening, I'm getting a "500 internal server error" for several hours when I try to get something like "http://epguides.frecar.no/show/bigbangtheory/next/", while "http://epguides.frecar.no/show/" and "http://epguides.frecar.no/show/bigbangtheory/info/" for instance work both perfectly fine.

**Comment by frecar** [comment]
Hi @fabbrus97 - I believe this should be resolved now?

**Comment by fabbrus97** [comment]
Yes, it' solved, thanks!
